spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/Spring?serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: dnjs9653

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none # create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB